// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE9qZQrBxYVq1oLOba7Zd2Ob9ggIX5WPI',
    appId: '1:622407992117:web:4ab8f119ad5bf18b86027c',
    messagingSenderId: '622407992117',
    projectId: 'product-catalogue-93156',
    authDomain: 'product-catalogue-93156.firebaseapp.com',
    storageBucket: 'product-catalogue-93156.appspot.com',
    measurementId: 'G-R91436GE8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK85nD8XvrLnC8tjPfRuuGO8XWY014Zxo',
    appId: '1:622407992117:android:a7cb083ef2e2af2986027c',
    messagingSenderId: '622407992117',
    projectId: 'product-catalogue-93156',
    storageBucket: 'product-catalogue-93156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeAAAgLnAe5tonka87Xh2gdPJPwTyaI-k',
    appId: '1:622407992117:ios:a0a609dc26636b6086027c',
    messagingSenderId: '622407992117',
    projectId: 'product-catalogue-93156',
    storageBucket: 'product-catalogue-93156.appspot.com',
    iosBundleId: 'com.example.productcatalogue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeAAAgLnAe5tonka87Xh2gdPJPwTyaI-k',
    appId: '1:622407992117:ios:a0a609dc26636b6086027c',
    messagingSenderId: '622407992117',
    projectId: 'product-catalogue-93156',
    storageBucket: 'product-catalogue-93156.appspot.com',
    iosBundleId: 'com.example.productcatalogue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE9qZQrBxYVq1oLOba7Zd2Ob9ggIX5WPI',
    appId: '1:622407992117:web:ea6cdafdb8bc562786027c',
    messagingSenderId: '622407992117',
    projectId: 'product-catalogue-93156',
    authDomain: 'product-catalogue-93156.firebaseapp.com',
    storageBucket: 'product-catalogue-93156.appspot.com',
    measurementId: 'G-0YGD3RXRFV',
  );
}
