// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPCfS6NgP5TyXtFpLhVW1vaPQT3O915U',
    appId: '1:207780824643:web:5de38b2b72df4b6482f6f6',
    messagingSenderId: '207780824643',
    projectId: 'chatapp-4d1a9',
    authDomain: 'chatapp-4d1a9.firebaseapp.com',
    storageBucket: 'chatapp-4d1a9.appspot.com',
    measurementId: 'G-4BNMFPVDG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeeyljskzuNPjD1rATeHhYfdMy__tt48',
    appId: '1:207780824643:android:68fed13edd286a7e82f6f6',
    messagingSenderId: '207780824643',
    projectId: 'chatapp-4d1a9',
    storageBucket: 'chatapp-4d1a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsEGhYSjX6ktbr8K5LDuhzHo-sGEELoFQ',
    appId: '1:207780824643:ios:10d604e82ee3c68982f6f6',
    messagingSenderId: '207780824643',
    projectId: 'chatapp-4d1a9',
    storageBucket: 'chatapp-4d1a9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsEGhYSjX6ktbr8K5LDuhzHo-sGEELoFQ',
    appId: '1:207780824643:ios:10d604e82ee3c68982f6f6',
    messagingSenderId: '207780824643',
    projectId: 'chatapp-4d1a9',
    storageBucket: 'chatapp-4d1a9.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPCfS6NgP5TyXtFpLhVW1vaPQT3O915U',
    appId: '1:207780824643:web:8d04e13d5053d53382f6f6',
    messagingSenderId: '207780824643',
    projectId: 'chatapp-4d1a9',
    authDomain: 'chatapp-4d1a9.firebaseapp.com',
    storageBucket: 'chatapp-4d1a9.appspot.com',
    measurementId: 'G-0XTDVTCPF3',
  );
}
