// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ3ukj-GpG-tVG10G0uhKt4HYsWpWsDYg',
    appId: '1:896271180951:web:a8bdeed2dec0caf381f5d2',
    messagingSenderId: '896271180951',
    projectId: 'fir-e8768',
    authDomain: 'fir-e8768.firebaseapp.com',
    storageBucket: 'fir-e8768.appspot.com',
    measurementId: 'G-YWKGXX6R62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpr2Vfhn4tazSdpDCgfWboRuIfAweZ9Q',
    appId: '1:896271180951:android:3db5c803eba423a981f5d2',
    messagingSenderId: '896271180951',
    projectId: 'fir-e8768',
    storageBucket: 'fir-e8768.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImDBrTsPfYmYe_3KgDCPz762IzZS_j3s',
    appId: '1:896271180951:ios:4345b1f51881c3a881f5d2',
    messagingSenderId: '896271180951',
    projectId: 'fir-e8768',
    storageBucket: 'fir-e8768.appspot.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImDBrTsPfYmYe_3KgDCPz762IzZS_j3s',
    appId: '1:896271180951:ios:4345b1f51881c3a881f5d2',
    messagingSenderId: '896271180951',
    projectId: 'fir-e8768',
    storageBucket: 'fir-e8768.appspot.com',
    iosBundleId: 'com.example.adminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ3ukj-GpG-tVG10G0uhKt4HYsWpWsDYg',
    appId: '1:896271180951:web:0700cce5a376b43381f5d2',
    messagingSenderId: '896271180951',
    projectId: 'fir-e8768',
    authDomain: 'fir-e8768.firebaseapp.com',
    storageBucket: 'fir-e8768.appspot.com',
    measurementId: 'G-L49GLWGYSX',
  );
}
